name: Cypress Regression Tests

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          browser: chrome
          jobs:
            api-tests:
              spec: cypress/e2e/api/**/*

            ui-tests:
              spec: cypress/e2e/ui/**/*
          record: true
        env:
          CYPRESS_BASE_URL: https://restful-booker.herokuapp.com
          CYPRESS_platformUrl: https://automationintesting.online
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Mochawesome
          path: cypress/reports
